import { access, readFile, readdir, rename } from 'node:fs/promises';
import { join } from 'node:path';
import { select } from '@inquirer/prompts';
import type { GeneratedFile } from './types.js';

export type MergeAction = 'merge' | 'replace' | 'skip';

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

export async function determineMergeAction(
  projectDir: string,
  force: boolean,
): Promise<MergeAction> {
  const claudeDir = join(projectDir, '.claude');
  if (!(await fileExists(claudeDir))) return 'replace';

  if (force) return 'replace';

  return select({
    message: 'Existing .claude/ directory found. What should we do?',
    choices: [
      { name: 'Merge (keep existing, add new)', value: 'merge' as const },
      { name: 'Replace (backup existing, generate fresh)', value: 'replace' as const },
      { name: 'Skip (abort)', value: 'skip' as const },
    ],
  });
}

export async function backupClaudeDir(projectDir: string): Promise<string> {
  const claudeDir = join(projectDir, '.claude');
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const backupDir = join(projectDir, `.claude.backup.${timestamp}`);
  await rename(claudeDir, backupDir);
  return backupDir;
}

export async function mergeSettingsJson(
  projectDir: string,
  generated: string,
): Promise<string> {
  const existingPath = join(projectDir, '.claude', 'settings.json');
  if (!(await fileExists(existingPath))) return generated;

  try {
    const existingContent = await readFile(existingPath, 'utf-8');
    const existing = JSON.parse(existingContent);
    const incoming = JSON.parse(generated);

    const merged = { ...existing };

    if (incoming.permissions) {
      merged.permissions = merged.permissions ?? {};
      const existingAllow = new Set(merged.permissions.allow ?? []);
      for (const perm of incoming.permissions.allow ?? []) {
        existingAllow.add(perm);
      }
      merged.permissions.allow = [...existingAllow];
    }

    if (incoming.hooks) {
      merged.hooks = merged.hooks ?? {};
      for (const hookType of Object.keys(incoming.hooks)) {
        const existingHooks: Array<{ command: string }> = merged.hooks[hookType] ?? [];
        const existingCommands = new Set(existingHooks.map((h: { command: string }) => h.command));
        for (const hook of incoming.hooks[hookType]) {
          if (!existingCommands.has(hook.command)) {
            existingHooks.push(hook);
          }
        }
        merged.hooks[hookType] = existingHooks;
      }
    }

    if (incoming.mcpServers) {
      merged.mcpServers = { ...merged.mcpServers, ...incoming.mcpServers };
    }

    return JSON.stringify(merged, null, 2);
  } catch {
    return generated;
  }
}

export async function mergeClaudeMd(
  projectDir: string,
  generated: string,
): Promise<string> {
  const existingPath = join(projectDir, '.claude', 'CLAUDE.md');
  if (!(await fileExists(existingPath))) return generated;

  try {
    const existing = await readFile(existingPath, 'utf-8');
    return `${existing.trimEnd()}\n\n---\n\n## Generated by cc-init\n\n${generated}`;
  } catch {
    return generated;
  }
}

export async function getExistingAgents(projectDir: string): Promise<Set<string>> {
  const agentsDir = join(projectDir, '.claude', 'agents');
  try {
    const entries = await readdir(agentsDir);
    return new Set(entries);
  } catch {
    return new Set();
  }
}

export function filterNewFiles(
  files: GeneratedFile[],
  existingAgents: Set<string>,
): GeneratedFile[] {
  return files.filter(f => {
    if (f.path.includes('/agents/')) {
      const filename = f.path.split('/').pop()!;
      return !existingAgents.has(filename);
    }
    return true;
  });
}
