import { describe, it, expect, afterEach } from 'vitest';
import { mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { mergeSettingsJson, mergeClaudeMd, getExistingAgents, filterNewFiles } from './merge.js';

const TEST_DIR = join(tmpdir(), 'cc-init-merge-test-' + Date.now());

async function setupDir(): Promise<string> {
  const dir = join(TEST_DIR, Math.random().toString(36).slice(2));
  await mkdir(join(dir, '.claude', 'agents'), { recursive: true });
  return dir;
}

afterEach(async () => {
  try { await rm(TEST_DIR, { recursive: true }); } catch { /* may not exist */ }
});

describe('merge', () => {
  it('merges settings.json permissions and hooks', async () => {
    const dir = await setupDir();
    await writeFile(join(dir, '.claude', 'settings.json'), JSON.stringify({
      permissions: { allow: ['Bash(git status)'] },
      hooks: { PostToolUse: [{ matcher: 'Write', command: 'prettier', description: 'old' }] },
    }));

    const generated = JSON.stringify({
      permissions: { allow: ['Bash(git status)', 'Bash(pnpm test)'] },
      hooks: { PostToolUse: [{ matcher: 'Write', command: 'eslint', description: 'new' }] },
      mcpServers: { playwright: { command: 'playwright' } },
    });

    const merged = JSON.parse(await mergeSettingsJson(dir, generated));

    expect(merged.permissions.allow).toContain('Bash(git status)');
    expect(merged.permissions.allow).toContain('Bash(pnpm test)');
    expect(merged.hooks.PostToolUse).toHaveLength(2);
    expect(merged.mcpServers.playwright.command).toBe('playwright');
  });

  it('appends generated CLAUDE.md content', async () => {
    const dir = await setupDir();
    await writeFile(join(dir, '.claude', 'CLAUDE.md'), '# Existing\n');

    const merged = await mergeClaudeMd(dir, '# New\n');

    expect(merged).toContain('# Existing');
    expect(merged).toContain('## Generated by cc-init');
    expect(merged).toContain('# New');
  });

  it('detects existing agents and filters duplicates', async () => {
    const dir = await setupDir();
    await writeFile(join(dir, '.claude', 'agents', 'reviewer.md'), 'existing');

    const existing = await getExistingAgents(dir);
    const filtered = filterNewFiles([
      { path: '.claude/agents/reviewer.md', content: 'new' },
      { path: '.claude/agents/security.md', content: 'new' },
      { path: '.claude/settings.json', content: '{}' },
    ], existing);

    expect(filtered.map(f => f.path)).not.toContain('.claude/agents/reviewer.md');
    expect(filtered.map(f => f.path)).toContain('.claude/agents/security.md');
    expect(filtered.map(f => f.path)).toContain('.claude/settings.json');
  });
});
